/**
 * Blank MCP Server Generator
 * Scaffolds a minimal MCP server with two example tools
 */

import fs from 'fs-extra';
import path from 'path';

export async function generateFromBlank({ name, outputDir, lang }) {
  const ts = lang === 'typescript';
  const ext = ts ? 'ts' : 'js';
  const displayName = String(name).replace(/[\r\n\u2028\u2029]+/g, ' ').replace(/\*\//g, '* /').trim();
  const markdownName = displayName
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/([\\\[\]|`])/g, '\\$1');
  const codeName = JSON.stringify(String(name));

  await fs.ensureDir(outputDir);
  await fs.ensureDir(path.join(outputDir, 'src'));
  await fs.ensureDir(path.join(outputDir, '.well-known'));

  const files = [];

  await fs.writeJson(path.join(outputDir, 'package.json'), {
    name,
    version: '0.1.0',
    description: `MCP server: ${name}`,
    type: 'module',
    scripts: ts
      ? { build: 'tsc', start: 'node dist/index.js', dev: 'tsx src/index.ts' }
      : { start: 'node src/index.js', dev: 'node --watch src/index.js' },
    dependencies: { '@modelcontextprotocol/sdk': '^1.0.0', dotenv: '^16.0.0' },
    devDependencies: ts ? { typescript: '^5.0.0', tsx: '^4.0.0', '@types/node': '^20.0.0' } : {},
  }, { spaces: 2 });
  files.push('package.json');

  if (ts) {
    await fs.writeJson(path.join(outputDir, 'tsconfig.json'), {
      compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
        outDir: './dist', rootDir: './src', strict: true, esModuleInterop: true, skipLibCheck: true,
      },
      include: ['src/**/*'],
    }, { spaces: 2 });
    files.push('tsconfig.json');
  }

  await fs.writeFile(path.join(outputDir, `src/index.${ext}`), `/**
 * ${displayName} MCP Server
 * Generated by create-mcp-server — https://agentappstore.dev
 *
 * Add your tools in src/tools.${ext}
 */

import 'dotenv/config';
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  ListToolsRequestSchema,
  CallToolRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { tools, callTool } from './tools.js';

const server = new Server(
  { name: ${codeName}, version: '0.1.0' },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools }));
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  return callTool(name, args ?? {});
});

const transport = new StdioServerTransport();
await server.connect(transport);
console.error(${JSON.stringify(`${name} MCP server running`)});
`);
  files.push(`src/index.${ext}`);

  await fs.writeFile(path.join(outputDir, `src/tools.${ext}`), `/**
 * Define your MCP tools here.
 * Each tool needs:
 *   - name: unique identifier (snake_case)
 *   - description: what it does (written for LLM reasoning)
 *   - inputSchema: JSON Schema for inputs
 */

${ts ? `import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';\n` : ''}
export const tools = [
  {
    name: 'example_echo',
    description: 'Echoes the input message back. Replace this with your real tool.',
    inputSchema: {
      type: 'object',
      properties: {
        message: { type: 'string', description: 'Message to echo' },
      },
      required: ['message'],
    },
  },
  {
    name: 'example_timestamp',
    description: 'Returns the current UTC timestamp.',
    inputSchema: {
      type: 'object',
      properties: {},
    },
  },
];

export async function callTool(
  name${ts ? ': string' : ''},
  args${ts ? ': Record<string, unknown>' : ''}
)${ts ? ': Promise<CallToolResult>' : ''} {
  switch (name) {
    case 'example_echo':
      return {
        content: [{ type: 'text', text: \`Echo: \${args.message}\` }],
      };

    case 'example_timestamp':
      return {
        content: [{ type: 'text', text: new Date().toISOString() }],
      };

    default:
      throw new Error(\`Unknown tool: \${name}\`);
  }
}
`);
  files.push(`src/tools.${ext}`);

  await fs.writeFile(path.join(outputDir, '.env.example'), `# ${displayName} environment variables\n# Copy to .env and fill in values\n\nAPI_BASE_URL=https://api.example.com\nAPI_KEY=your-key-here\n`);
  files.push('.env.example');

  await fs.writeFile(path.join(outputDir, '.gitignore'), 'node_modules/\ndist/\n.env\n');
  files.push('.gitignore');

  await fs.writeFile(path.join(outputDir, 'README.md'), `# ${markdownName}\n\nMCP server generated by [Agent App Store](https://agentappstore.dev).\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nEdit \`src/tools.${ext}\` to add your tools.\n`);
  files.push('README.md');

  return {
    name,
    files,
    description: `MCP server: ${name}`,
    capabilities: [],
    authType: 'none',
  };
}
